apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thdblog-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/tracking-id: tienhoangdevblog:networking.k8s.io/Ingress:argocd/thdblog-ingress
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: wiki.polodev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: thdblog-service
                port:
                  number: 80

  tls:
    - hosts:
        - wiki.polodev.com
      secretName: wiki-polodev-tls
status:
  loadBalancer:
    ingress:
    - {}
