apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thdblog-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / # For some NGINX versions
spec:
  ingressClassName: nginx # Important: specifies to use the NGINX Ingress Controller
  rules:
  - host: polodev.com # Replace with your actual domain or use a test domain
    http:
      paths:
      - path: /blog
        pathType: Prefix
        backend:
          service:
            name: thdblog-service
            port:
              number: 80
