apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: tienhoangdevblog:networking.k8s.io/Ingress:argocd/thdblog-ingress
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: thdblog-ingress
  namespace: argocd
spec:
  ingressClassName: nginx
  rules:
    - host: wiki.polodev.com
      http:
        paths:
          - backend:
              service:
                name: thdblog-service
                port:
                  number: 80 # Nginx handles SSL, forwards HTTP to service
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - wiki.polodev.com
      secretName: wiki-polodev-tls # Cert-Manager will create/update this
