apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
  - protocol: TCP
    port: 80 # Port the service will be available on within the cluster
    targetPort: 80 # Port on the pod
  type: ClusterIP
